import { HeaderPost, ImgPost } from "./component.header";
import {
  ContainerFormPost,
  GridFormPost,
  InputPost,
  ImgPostForm,
  FormPost,
  GridButtonsPost,
  ButtonsPost,
  TextareaPost,
  GridImgPost,
  InputFilePost,
  InputLabelPost,
  ButtonRemoveImgPost,
} from "./component.formcreatepost";

import {
  ContainerPost,
  GridPost,
  TextFeedPost,
  HeaderRemovePost,
  ButtonRemovePost, 
  GridImgPublish, 
  GridPostInfo,
  ImgPublishPost, 
  TextoPublishPost,
  GridTextsPost,
  TextNamePost,
  TextSenderPost, 
  GridPusblishByWhom
} from "./component.publish.post";

export {
  HeaderPost,
  ImgPost,
  ContainerFormPost,
  GridFormPost,
  InputPost,
  ImgPostForm,
  FormPost,
  GridButtonsPost,
  ButtonsPost,
  TextareaPost,
  GridImgPost,
  InputFilePost,
  InputLabelPost,
  ButtonRemoveImgPost,
  ContainerPost,
  GridPost,
  TextFeedPost,
  HeaderRemovePost,
  ButtonRemovePost, 
  GridImgPublish, 
  GridPostInfo,
  ImgPublishPost, 
  TextoPublishPost, 
  GridTextsPost, 
  TextNamePost,
  TextSenderPost, 
  GridPusblishByWhom
};
