import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./Componentes/NavBar/navBar";
import ThemeSelector from "./Componentes/ThemeSelector/ThemeSelector";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-verdeE dark:bg-azulE text-white ">
        <div>
          <NavBar />

          {children}
        </div>
      </body>
    </html>
  );
}
