import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Container from 'react-bootstrap/Container'
import HeaderBar from '../components/HeaderBar'


export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderBar />
    </Container>
  )
}
