import type { Metadata } from 'next'
import './globals.css'
import { inter } from './font'
import { Header } from '@/components/header/header'

export const metadata: Metadata = {
  title: 'Web Developer Challenge',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={`bg-zinc-700 ${inter.className}`}>
        <Header />
        <div className="max-w-[1200px] mx-auto">{children}</div>
      </body>
    </html>
  )
}
