import { Metadata } from 'next';
import { CardInputContainer } from './components/cardInput';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};
export default function Home() {
	return (
		<div>
			<CardInputContainer />
		</div>
	);
}
